# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2b64b5849fc5c41e8a99534d7afa255a797189be5c60f209e2588ad3b9a2038c5569013fc6e15c9ae455e5830067be7188e57f85dd9e9e35c6a6ab8681ab86

test:
  secret_key_base: 4226f51dad4219a24ddc968c6e489362836901f9a84d1622623013d4a64e507a7aeb0329a90bf7945d4942ab7da5fef361fed1dafbf7b86680954f12f1f403ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
